name: Regression Resource Check

on:
  pull_request:
    branches: [develop]
  push:
    branches: ['**']
  workflow_dispatch:

defaults:
  run:
    shell: bash -leo pipefail {0}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env: 
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MACHINES: "acorn derecho gaeac6 hera hercules orion ursa wcoss2"
  BASE_URL: https://api.github.com/repos/ufs-community/ufs-weather-model
  PR_NUM: ${{ github.event.number }}

jobs:
  get-historical-data: #Add: If already exists, don't run again! 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout feature branch
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pip install requests numpy
      - name: Get develop branch commits
        run: python .github/scripts/parse_historical_data.py
      - name: Upload json
        uses: actions/upload-artifact@v4
        with: 
          name: stats.json
          path: ${{ github.workspace }}/stats.json
  compare-resources:
    runs-on: ubuntu-latest
    needs: get-historical-data
    steps:
      - name: Checkout feature branch
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pip install requests numpy
      - name: Download historical data
        uses: actions/download-artifact@v5
        with: 
          name: stats.json
          path: ${{ github.workspace }}
      - name: Fetch baseline logs and check stats
        run: |
          python ${{ github.workspace }}/.github/scripts/compare_logs.py
        env: 
          MACHINE_STATS: ${{ github.workspace }}/stats.json
      - name: Upload results
        uses: actions/upload-artifact@v4
        with: 
          name: test_results.json
          path: ${{ github.workspace }}/test_results.json
  write-results:  
    runs-on: ubuntu-latest
    needs: compare-resources
    steps:
      - name: Checkout feature branch
        uses: actions/checkout@v4
      - name: Download test results
        uses: actions/download-artifact@v5
        with: 
          name: test_results.json
          path: ${{ github.workspace }}
        env: 
          RESULTS: ${{ github.workspace }}/test_results.json
      - name: Write results summary
        run: |
          python ${{ github.workspace }}/.github/scripts/write_test_summary.py >> $GITHUB_STEP_SUMMARY
